name: Auto Upload to Packagist

on:
  push:
    branches:
      - main # O la rama que desees usar para hacer el push (usualmente "main" o "master")

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # O cualquier versión de PHP que prefieras usar

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Publish to Packagist
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -sSL https://github.com/packagist/composer-publish/releases/download/v1.1.0/composer-publish.phar -o composer-publish.phar
          php composer-publish.phar --token $PACKAGIST_TOKEN
